### https://github.com/marketplace/actions/open-journals-pdf-generator
### https://joss.readthedocs.io/en/latest/submitting.html
### Build JOSS paper
### .github/workflows/draft-pdf.yml
### https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions
### https://ashki23.github.io/markdown-latex.html


on:
  push:
    branches:
      - joss

jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    name: Paper Draft
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build draft PDF
      uses: openjournals/openjournals-draft-action@master
      # "paper-path:" i should be the path to the paper within your repo.
      with:
        journal: joss
        paper-path: ./paper/paper.md
    - name: Upload
      uses: actions/upload-artifact@v1
      # "path:" is the output path where Pandoc will write the compiled
      # PDF. Note, this should be the same directory as the input
      # paper.md
      with:
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        name: paper
        path: ./paper/paper.pdf


