### https://github.com/marketplace/actions/open-journals-pdf-generator
### https://joss.readthedocs.io/en/latest/submitting.html
### Build JOSS paper
### .github/workflows/draft-pdf.yml
### https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions
### https://ashki23.github.io/markdown-latex.html

on:
  push:
    branches:
      - joss

jobs:
  paper:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    name: Paper Draft
    steps:
    - name: Open Journals PDF Generator
      description: Create a draft PDF for an Open Journals paper
      inputs:
       journal: joss
         description: Target journal, must be either "joss" or "jose"
         required: false
         default: joss
        paper-path: ./paper/paper.md
          description: >-
              Path to the main paper Markdown file, relative to the
              project's root directory.
          required: false
          default: 'paper.md'
      runs:
        using: docker
        image: 'docker://openjournals/inara:latest'
        env:
          # GIT_SHA: $GITHUB_SHA
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
          JOURNAL: ${{ inputs.journal }}
        args:
          - -o pdf
          - ${{ inputs.paper-path }}
      branding:
        icon: file-text
        color: blue
    - name: Upload
      uses: actions/upload-artifact@v1
      # "path:" is the output path where Pandoc will write the compiled
      # PDF. Note, this should be the same directory as the input
      # paper.md
      with:
        # branch: joss_test
        # github_token: ${{ secrets.GITHUB_TOKEN }}
        name: paper
        path: ./paper/paper.pdf



